server.port=8080

spring.datasource.platform=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

application.security.jwt.secret-key=o5fcvzcKE38XYnKKhOMNKhnQSR5EFmuZ
application.security.jwt.expiration=86400000  
# a day
application.security.jwt.refresh-token.expiration=604800000
# 7 days
