<<<<<<< HEAD
# Active profile is supplied externally by the deployment environment.
# DEV  -> SPRING_PROFILES_ACTIVE=dev
# PROD -> SPRING_PROFILES_ACTIVE=prod
# Default profile used when SPRING_PROFILES_ACTIVE is not set externally.

spring.profiles.active=dev
=======
#dont touch this file 
# Active profile is supplied externally by the deployment environment.
# DEV  -> SPRING_PROFILES_ACTIVE=dev
# PROD -> SPRING_PROFILES_ACTIVE=prod
>>>>>>> f2385397dfbceb684f87121903fcdd27e323b20c
